/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/direct_messages": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.direct_messages.id"];
          created_at?: parameters["rowFilter.direct_messages.created_at"];
          updated_at?: parameters["rowFilter.direct_messages.updated_at"];
          content?: parameters["rowFilter.direct_messages.content"];
          from_id?: parameters["rowFilter.direct_messages.from_id"];
          to_id?: parameters["rowFilter.direct_messages.to_id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["direct_messages"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** direct_messages */
          direct_messages?: definitions["direct_messages"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.direct_messages.id"];
          created_at?: parameters["rowFilter.direct_messages.created_at"];
          updated_at?: parameters["rowFilter.direct_messages.updated_at"];
          content?: parameters["rowFilter.direct_messages.content"];
          from_id?: parameters["rowFilter.direct_messages.from_id"];
          to_id?: parameters["rowFilter.direct_messages.to_id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.direct_messages.id"];
          created_at?: parameters["rowFilter.direct_messages.created_at"];
          updated_at?: parameters["rowFilter.direct_messages.updated_at"];
          content?: parameters["rowFilter.direct_messages.content"];
          from_id?: parameters["rowFilter.direct_messages.from_id"];
          to_id?: parameters["rowFilter.direct_messages.to_id"];
        };
        body: {
          /** direct_messages */
          direct_messages?: definitions["direct_messages"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/profiles": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles.id"];
          name?: parameters["rowFilter.profiles.name"];
          avatar?: parameters["rowFilter.profiles.avatar"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["profiles"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** profiles */
          profiles?: definitions["profiles"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles.id"];
          name?: parameters["rowFilter.profiles.name"];
          avatar?: parameters["rowFilter.profiles.avatar"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles.id"];
          name?: parameters["rowFilter.profiles.name"];
          avatar?: parameters["rowFilter.profiles.avatar"];
        };
        body: {
          /** profiles */
          profiles?: definitions["profiles"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/profiles_private": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles_private.id"];
          email?: parameters["rowFilter.profiles_private.email"];
          admin?: parameters["rowFilter.profiles_private.admin"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["profiles_private"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** profiles_private */
          profiles_private?: definitions["profiles_private"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles_private.id"];
          email?: parameters["rowFilter.profiles_private.email"];
          admin?: parameters["rowFilter.profiles_private.admin"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles_private.id"];
          email?: parameters["rowFilter.profiles_private.email"];
          admin?: parameters["rowFilter.profiles_private.admin"];
        };
        body: {
          /** profiles_private */
          profiles_private?: definitions["profiles_private"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/room_messages": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.room_messages.id"];
          created_at?: parameters["rowFilter.room_messages.created_at"];
          updated_at?: parameters["rowFilter.room_messages.updated_at"];
          content?: parameters["rowFilter.room_messages.content"];
          user_id?: parameters["rowFilter.room_messages.user_id"];
          room_id?: parameters["rowFilter.room_messages.room_id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["room_messages"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** room_messages */
          room_messages?: definitions["room_messages"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.room_messages.id"];
          created_at?: parameters["rowFilter.room_messages.created_at"];
          updated_at?: parameters["rowFilter.room_messages.updated_at"];
          content?: parameters["rowFilter.room_messages.content"];
          user_id?: parameters["rowFilter.room_messages.user_id"];
          room_id?: parameters["rowFilter.room_messages.room_id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.room_messages.id"];
          created_at?: parameters["rowFilter.room_messages.created_at"];
          updated_at?: parameters["rowFilter.room_messages.updated_at"];
          content?: parameters["rowFilter.room_messages.content"];
          user_id?: parameters["rowFilter.room_messages.user_id"];
          room_id?: parameters["rowFilter.room_messages.room_id"];
        };
        body: {
          /** room_messages */
          room_messages?: definitions["room_messages"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/rooms": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.rooms.id"];
          created_at?: parameters["rowFilter.rooms.created_at"];
          updated_at?: parameters["rowFilter.rooms.updated_at"];
          slug?: parameters["rowFilter.rooms.slug"];
          name?: parameters["rowFilter.rooms.name"];
          topic?: parameters["rowFilter.rooms.topic"];
          user_id?: parameters["rowFilter.rooms.user_id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["rooms"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** rooms */
          rooms?: definitions["rooms"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.rooms.id"];
          created_at?: parameters["rowFilter.rooms.created_at"];
          updated_at?: parameters["rowFilter.rooms.updated_at"];
          slug?: parameters["rowFilter.rooms.slug"];
          name?: parameters["rowFilter.rooms.name"];
          topic?: parameters["rowFilter.rooms.topic"];
          user_id?: parameters["rowFilter.rooms.user_id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.rooms.id"];
          created_at?: parameters["rowFilter.rooms.created_at"];
          updated_at?: parameters["rowFilter.rooms.updated_at"];
          slug?: parameters["rowFilter.rooms.slug"];
          name?: parameters["rowFilter.rooms.name"];
          topic?: parameters["rowFilter.rooms.topic"];
          user_id?: parameters["rowFilter.rooms.user_id"];
        };
        body: {
          /** rooms */
          rooms?: definitions["rooms"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/rpc/unaccent_lexize": {
    post: {
      parameters: {
        body: {
          args: {
            "": string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/handle_new_user": {
    post: {
      parameters: {
        body: {
          args: { [key: string]: unknown };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/get_conversations": {
    post: {
      parameters: {
        body: {
          args: { [key: string]: unknown };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/post_message_to_room": {
    post: {
      parameters: {
        body: {
          args: {
            room_slug: string;
            content: string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/unaccent_init": {
    post: {
      parameters: {
        body: {
          args: {
            "": string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/unaccent": {
    post: {
      parameters: {
        body: {
          args: {
            "": string;
          };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/slugify": {
    post: {
      parameters: {
        body: {
          args: { [key: string]: unknown };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
}

export interface definitions {
  direct_messages: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    created_at: string;
    updated_at: string;
    content: string;
    /**
     * Note:
     * This is a Foreign Key to `profiles.id`.<fk table='profiles' column='id'/>
     */
    from_id: string;
    /**
     * Note:
     * This is a Foreign Key to `profiles.id`.<fk table='profiles' column='id'/>
     */
    to_id: string;
  };
  profiles: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    name: string;
    avatar: string;
  };
  profiles_private: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     * This is a Foreign Key to `profiles.id`.<fk table='profiles' column='id'/>
     */
    id: string;
    email: string;
    admin: boolean;
  };
  room_messages: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    created_at: string;
    updated_at: string;
    content: string;
    /**
     * Note:
     * This is a Foreign Key to `profiles.id`.<fk table='profiles' column='id'/>
     */
    user_id: string;
    /**
     * Note:
     * This is a Foreign Key to `rooms.id`.<fk table='rooms' column='id'/>
     */
    room_id: string;
  };
  rooms: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    created_at: string;
    updated_at: string;
    slug: string;
    name: string;
    topic: string;
    /**
     * Note:
     * This is a Foreign Key to `profiles.id`.<fk table='profiles' column='id'/>
     */
    user_id: string;
  };
}

export interface parameters {
  /** Preference */
  preferParams: "params=single-object";
  /** Preference */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /** Preference */
  preferCount: "count=none";
  /** Filtering Columns */
  select: string;
  /** On Conflict */
  on_conflict: string;
  /** Ordering */
  order: string;
  /** Limiting and Pagination */
  range: string;
  /** Limiting and Pagination */
  rangeUnit: string;
  /** Limiting and Pagination */
  offset: string;
  /** Limiting and Pagination */
  limit: string;
  /** direct_messages */
  "body.direct_messages": definitions["direct_messages"];
  "rowFilter.direct_messages.id": string;
  "rowFilter.direct_messages.created_at": string;
  "rowFilter.direct_messages.updated_at": string;
  "rowFilter.direct_messages.content": string;
  "rowFilter.direct_messages.from_id": string;
  "rowFilter.direct_messages.to_id": string;
  /** profiles */
  "body.profiles": definitions["profiles"];
  "rowFilter.profiles.id": string;
  "rowFilter.profiles.name": string;
  "rowFilter.profiles.avatar": string;
  /** profiles_private */
  "body.profiles_private": definitions["profiles_private"];
  "rowFilter.profiles_private.id": string;
  "rowFilter.profiles_private.email": string;
  "rowFilter.profiles_private.admin": string;
  /** room_messages */
  "body.room_messages": definitions["room_messages"];
  "rowFilter.room_messages.id": string;
  "rowFilter.room_messages.created_at": string;
  "rowFilter.room_messages.updated_at": string;
  "rowFilter.room_messages.content": string;
  "rowFilter.room_messages.user_id": string;
  "rowFilter.room_messages.room_id": string;
  /** rooms */
  "body.rooms": definitions["rooms"];
  "rowFilter.rooms.id": string;
  "rowFilter.rooms.created_at": string;
  "rowFilter.rooms.updated_at": string;
  "rowFilter.rooms.slug": string;
  "rowFilter.rooms.name": string;
  "rowFilter.rooms.topic": string;
  "rowFilter.rooms.user_id": string;
}

export interface operations {}

export interface external {}
